# Generated by Django 5.0.7 on 2024-09-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybertea_app', '0005_rename_category_image_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
