# Generated by Django 5.0.7 on 2024-09-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybertea_app', '0006_delete_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='../imgs/'),
        ),
    ]
